clc;
clear;
N=1000;
T=1:1:N;
Input=normrnd(0,30,1,N);
TF1=tf([1],[2,1]);
TF2=tf([0.25],[1,0.7071,0.25]);
Output1=(lsim(TF1,Input,T))';
Output2=(lsim(TF2,Input,T))';
[Acof_Input,Lag_Input]=xcorr(Input);
[Acof_Output1,Lag_Output1]=xcorr(Output1);
[Acof_Output2,Lag_Output2]=xcorr(Output2);
InputF=(fft(Input));
Output1F=(fft(Output1));
Output2F=(fft(Output2));
[Acof_InputF,Lag_InputF]=xcorr(InputF);
[Acof_Output1F,Lag_Output1F]=xcorr(Output1F);
[Acof_Output2F,Lag_Output2F]=xcorr(Output2F);
Acof_InputArea=trapz(Acof_Input)
Acof_Output1Area=trapz(Acof_Output1)
Acof_Output2Area=trapz(Acof_Output2)
Acof_InputFArea=abs(trapz(Acof_InputF))
Acof_Output1FArea=abs(trapz(Acof_Output1F))
Acof_Output2FArea=abs(trapz(Acof_Output2F))
% figure(1);
% subplot(4,3,1);
% plot(T,Input,'bo-');
% title('Time Sequence of input Gaussian white with $\mu=0\,\sigma=30$','interpreter','latex');
% xlabel('Sequence (s)');
% ylabel('Singnal Amplitude');
% ylim([-100 100]);
% subplot(4,3,2);
% plot(T,Output1,'r+--');
% title('Time Sequence of first filter output','interpreter','latex');
% xlabel('Sequence (s)');
% ylabel('Singnal Amplitude');
% ylim([-75 75]);
% subplot(4,3,3);
% plot(T,Output2,'m*-.')
% ylim([-50 50]);
% title('Time Sequence of second filter output','interpreter','latex');
% xlabel('Sequence (s)');
% ylabel('Singnal Amplitude');
% figure(2);
% subplot(2,1,1);
% plot(T,Input,'bo-',T,Output1,'k+--',T,Output2,'m*-.');
% xlim([0 100]);
% title('Comparison of input and output signal in time domain','interpreter','latex');
% xlabel('Sequence (s)');
% ylabel('Singnal Amplitude');
% legend('Input','Output of 1st filter','Output of 2nd filter');
% figure(1);
% subplot(4,3,4);
% histfit(Input,30,'normal');
% xlim([-100 100]);
% title('Histogram of input Gaussian white with $\mu=0\,\sigma=30$','interpreter','latex');
% legend('Histogram','Fitting Curve');
% xlabel('Range of amplitude');
% ylabel('Number of each range');
% subplot(4,3,5);
% histfit(Output1,30,'normal');
% xlim([-100 100]);
% title('Histogram of output signal with 1st filter','interpreter','latex');
% legend('Histogram','Fitting Curve');
% xlabel('Range of amplitude');
% ylabel('Number of each range');
% subplot(4,3,6);
% histfit(Output2,30,'normal');
% xlim([-100 100]);
% title('Histogram of output signal with 2nd filter','interpreter','latex');
% legend('Histogram','Fitting Curve');
% xlabel('Range of amplitude');
% ylabel('Number of each range');
% subplot(4,3,7);
% plot(Lag_Input,Acof_Input./Acof_InputArea);
% title('Autocorrelation of input signal with $\mu=0\,\sigma=30$','interpreter','latex');
% xlabel('Lag');
% subplot(4,3,8);
% plot(Lag_Output1,Acof_Output1./Acof_Output1Area);
% title('Autocorrelation of output signal from 1st filter','interpreter','latex');
% xlabel('Lag');
% subplot(4,3,9);
% plot(Lag_Output2,Acof_Output2./Acof_Output2Area);
% title('Autocorrelation of output signal from 2nd filter','interpreter','latex');
% xlabel('Lag');
% figure(2);
% subplot(2,1,2);
% plot(Lag_Input,Acof_Input./Acof_InputArea,'bo-',Lag_Output1,Acof_Output1./Acof_Output1Area,'r+-',Lag_Output2,Acof_Output2./Acof_Output2Area,'m*-');
% xlim([-50 50]);
% title('Comparsion of autocorrelation coefficient','interpreter','latex');
% legend('Input','Output from 1st filter','Output from 2nd filter');
% xlabel('Lag');
% figure(1);
% subplot(4,3,10);
% periodogram(Input,rectwin(length(Input)),length(Input));
% title('Autospectral density function of input signal $\mu = 0 , \sigma = 30$','Interpreter','latex');
% subplot(4,3,11);
% periodogram(Output1,rectwin(length(Output1)),length(Output1));
% title('Autospectral density function of output signal from 1st filter','Interpreter','latex');
% subplot(4,3,12);
% periodogram(Output2,rectwin(length(Output2)),length(Output2));
% title('Autospectral density function of output signal from 2nd filter','Interpreter','latex');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
figure(3);
plot(T,Input,'bo-',T,Output1,'r+-',T,Output2,'k*-')
title('Amplitude of each frequencies with signal after FFT');
xlabel('Hz');
ylabel('Amplitude');
legend('Input','Output of filter 1','Output of filter 2');
figure(4);
subplot(3,1,1);
plot(Lag_InputF,Acof_InputF./Acof_InputFArea);
title('Autocorrelation of input signal in frequency domain by FFT');
xlabel('Lag');
ylabel('Autocorrelation coefficient');
xlim([-50 50]);
subplot(3,1,2);
plot(Lag_Output1F,Acof_Output1F./Acof_Output1FArea);
title('Autocorrelation of output signal from 1st filter in frequency domain by FFT');
xlabel('Lag');
xlim([-50 50]);
subplot(3,1,3);
plot(Lag_Output2F,Acof_Output2F./Acof_Output2FArea);
title('Autocorrelation of output signal from 2nd filter in frequency domain by FFT');
xlabel('Lag');
xlim([-50 50]);
figure(5);
plot(Lag_InputF,Acof_InputF./Acof_InputFArea,'bo-',Lag_Output1F,Acof_Output1F./Acof_Output1FArea,'r+--',Lag_Output2F,Acof_Output2F./Acof_Output2FArea,'k*-.');
xlim([-50 50]);
title('Comparison of the autocorrelation coefficient in frequency domian');
legend('Input','Output from 1st filter','Output from 2nd filter');
xlabel('Lag');
