clc;
clear;
N=10000;
T=1:1:N;
R=normrnd(0,30,1,N);
R2=normrnd(0,30,1,N);
for i=1:1:N
    [R_Muller1(i),R_Muller2(i)]=BoxMuller(0,30);
end
[Acor,Lag]=xcorr(R);
[Acor1,Lag1]=xcorr(R_Muller1);
AreaAcor=trapz(Acor);
AreaAcor1=trapz(Acor1)

% figure(1);
% subplot(2,1,1);
% plot(T,R,'b');
% F=title('Time sequence of normrnd $\mu = 0 , \sigma = 30$','Interpreter','latex');
% F.FontSize=15;
% F=xlabel('Sequence');
% F.FontSize=15;
% F=ylabel('Output of normrnd');
% F.FontSize=15;
% ylim([-150 150]);
% subplot(2,1,2);
% histfit(R,30,'normal');
% F=title('Histogram of normrnd $\mu = 0 , \sigma = 30$','Interpreter','latex');
% F.FontSize=15;
% F=xlabel('Range of output');
% F.FontSize=15;
% F=ylabel('Number of each range');
% F.FontSize=15;
% legend('Histogram','Fittinf of distribution');
% xlim([-100 100]);
% figure(2);
% subplot(2,1,1);
% H=plot(Lag,Acor/AreaAcor,'b');
% H.LineWidth=2;
% F=title('Autocorrlation of normrnd $\mu = 0 , \sigma = 30$','Interpreter','latex');
% F.FontSize=15;
% F=xlabel('Lag of sequence');
% F.FontSize=15;
% subplot(2,1,2);
% periodogram(R,rectwin(length(R)),length(R));
% F=title('Autospectral density function of normrnd $\mu = 0 , \sigma = 30$','Interpreter','latex');
% F.FontSize=15;

figure(3);
subplot(2,1,1);
plot(T,R_Muller1);
ylim([-150 150]);
F=title('Time sequence of Box-Muller $\mu = 0 , \sigma = 30$','Interpreter','latex');
F.FontSize=15;
F=xlabel('Sequence');
F.FontSize=15;
F=ylabel('Output of normrnd');
subplot(2,1,2);
F.FontSize=15;
histfit(R_Muller1,30,'normal');
xlim([-100 100]);
F=title('Histogram of Box-Muller $\mu = 0 , \sigma = 30$','Interpreter','latex');
F.FontSize=15;
F=xlabel('Range of output');
F.FontSize=15;
F=ylabel('Number of each range');
F.FontSize=15;
legend('Histogram','Fittinf of distribution');
figure(4);
subplot(2,1,1);
plot(Lag1,Acor1./AreaAcor1);
F=title('Autocorrlation of Box-Muller $\mu = 0 , \sigma = 30$','Interpreter','latex');
F.FontSize=15;
F=xlabel('Lag of sequence');
F.FontSize=15;
subplot(2,1,2);
periodogram(R_Muller1,rectwin(length(R_Muller1)),length(R_Muller1));
F=title('Autospectral density function of Box-Muller $\mu = 0 , \sigma = 30$','Interpreter','latex');
F.FontSize=15;

