clc;
clear;
N=10000;
t=1:1:N;
min=0;
for j=1:1:5
    max=10*j;
    for i=1:1:N
        U(j,i)=UniRand(0,max);
        MeanSequence(j,i)=mean(U(j,1:i));
        STDSequence(j,i)=std(U(j,1:i));
    end
    MEAN_Est(j)=mean(U(j,:));
    MEAN(j)=(max+min)/2;
    STD_Est(j)=std(U(j,:));
    STD(j)=(max-min)/sqrt(12);
end
figure(1);
subplot(3,2,1);
histogram(U(1,:),10);
title(strcat('$\mu\,=\,$',num2str(MEAN(1)),',','$\,\sigma\,=\,$',num2str(STD(1)),'\,,\,','N\,=\,',int2str(N)),'Interpreter','latex');
xlabel('Output of UniRand');
ylabel('Nmber of each range');
subplot(3,2,2);
histogram(U(2,:),10);
title(strcat('$\mu\,=\,$',num2str(MEAN(2)),',','$\,\sigma\,=\,$',num2str(STD(2)),'\,,\,','N\,=\,',int2str(N)),'Interpreter','latex');
xlabel('Output of UniRand');
ylabel('Nmber of each range');
subplot(3,2,3);
histogram(U(3,:),10);
title(strcat('$\mu\,=\,$',num2str(MEAN(3)),',','$\,\sigma\,=\,$',num2str(STD(3)),'\,,\,','N\,=\,',int2str(N)),'Interpreter','latex');
xlabel('Output of UniRand');
ylabel('Nmber of each range');
subplot(3,2,4);
histogram(U(4,:),10);
title(strcat('$\mu\,=\,$',num2str(MEAN(4)),',','$\,\sigma\,=\,$',num2str(STD(4)),'\,,\,','N\,=\,',int2str(N)),'Interpreter','latex');
xlabel('Output of UniRand');
ylabel('Nmber of each range');
subplot(3,2,5);
histogram(U(5,:),10);
title(strcat('$\mu\,=\,$',num2str(MEAN(5)),',','$\,\sigma\,=\,$',num2str(STD(5)),'\,,\,','N\,=\,',int2str(N)),'Interpreter','latex');
xlabel('Output of UniRand');
ylabel('Nmber of each range');

figure(2);
subplot(3,2,1);
semilogx(t,MeanSequence(1,:));
title(strcat('$\mu\,=\,$',num2str(MEAN(1)),',','$\,\sigma\,=\,$',num2str(STD(1)),'\,,\,','N\,=\,',int2str(N)),'Interpreter','latex');
xlabel('Sequence');
ylabel('Mean');
subplot(3,2,2);
semilogx(t,MeanSequence(2,:));
title(strcat('$\mu\,=\,$',num2str(MEAN(2)),',','$\,\sigma\,=\,$',num2str(STD(2)),'\,,\,','N\,=\,',int2str(N)),'Interpreter','latex');
xlabel('Sequence');
ylabel('Mean');
subplot(3,2,3);
semilogx(t,MeanSequence(3,:));
title(strcat('$\mu\,=\,$',num2str(MEAN(3)),',','$\,\sigma\,=\,$',num2str(STD(3)),'\,,\,','N\,=\,',int2str(N)),'Interpreter','latex');
xlabel('Sequence');
ylabel('Mean');
subplot(3,2,4);
semilogx(t,MeanSequence(4,:));
title(strcat('$\mu\,=\,$',num2str(MEAN(4)),',','$\,\sigma\,=\,$',num2str(STD(4)),'\,,\,','N\,=\,',int2str(N)),'Interpreter','latex');
xlabel('Sequence');
ylabel('Mean');
subplot(3,2,5);
semilogx(t,MeanSequence(5,:));
title(strcat('$\mu\,=\,$',num2str(MEAN(5)),',','$\,\sigma\,=\,$',num2str(STD(5)),'\,,\,','N\,=\,',int2str(N)),'Interpreter','latex');
xlabel('Sequence');
ylabel('Mean');

figure(3);
subplot(3,2,1);
semilogx(t,STDSequence(1,:));
title(strcat('$\mu\,=\,$',num2str(MEAN(1)),',','$\,\sigma\,=\,$',num2str(STD(1)),'\,,\,','N\,=\,',int2str(N)),'Interpreter','latex');
xlabel('Sequence');
ylabel('STD');
subplot(3,2,2);
semilogx(t,STDSequence(2,:));
title(strcat('$\mu\,=\,$',num2str(MEAN(2)),',','$\,\sigma\,=\,$',num2str(STD(2)),'\,,\,','N\,=\,',int2str(N)),'Interpreter','latex');
xlabel('Sequence');
ylabel('STD');
subplot(3,2,3);
semilogx(t,STDSequence(3,:));
title(strcat('$\mu\,=\,$',num2str(MEAN(3)),',','$\,\sigma\,=\,$',num2str(STD(3)),'\,,\,','N\,=\,',int2str(N)),'Interpreter','latex');
xlabel('Sequence');
ylabel('STD');
subplot(3,2,4);
semilogx(t,STDSequence(4,:));
title(strcat('$\mu\,=\,$',num2str(MEAN(4)),',','$\,\sigma\,=\,$',num2str(STD(4)),'\,,\,','N\,=\,',int2str(N)),'Interpreter','latex');
xlabel('Sequence');
ylabel('STD');
subplot(3,2,5);
semilogx(t,STDSequence(5,:));
title(strcat('$\mu\,=\,$',num2str(MEAN(5)),',','$\,\sigma\,=\,$',num2str(STD(5)),'\,,\,','N\,=\,',int2str(N)),'Interpreter','latex');
xlabel('Sequence');
ylabel('STD');
